<?php

/**
 * BaseRequirement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $repository_id
 * @property enum $type
 * @property string $value
 * @property Repository $Repository
 * 
 * @method integer     getRepositoryId()  Returns the current record's "repository_id" value
 * @method enum        getType()          Returns the current record's "type" value
 * @method string      getValue()         Returns the current record's "value" value
 * @method Repository  getRepository()    Returns the current record's "Repository" value
 * @method Requirement setRepositoryId()  Sets the current record's "repository_id" value
 * @method Requirement setType()          Sets the current record's "type" value
 * @method Requirement setValue()         Sets the current record's "value" value
 * @method Requirement setRepository()    Sets the current record's "Repository" value
 * 
 * @package    symfohub
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRequirement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('requirement');
        $this->hasColumn('repository_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'symfony',
              1 => 'doctrine',
              2 => 'propel',
              3 => 'view',
              4 => 'nosql',
              5 => 'javascript',
              6 => 'license',
             ),
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Repository', array(
             'local' => 'repository_id',
             'foreign' => 'id'));
    }
}