<?php

/**
 * BaseRequirment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $repostory_id
 * @property enum $type
 * @property string $name
 * @property string $version
 * @property Repository $Repository
 * 
 * @method integer    getRepostoryId()  Returns the current record's "repostory_id" value
 * @method enum       getType()         Returns the current record's "type" value
 * @method string     getName()         Returns the current record's "name" value
 * @method string     getVersion()      Returns the current record's "version" value
 * @method Repository getRepository()   Returns the current record's "Repository" value
 * @method Requirment setRepostoryId()  Sets the current record's "repostory_id" value
 * @method Requirment setType()         Sets the current record's "type" value
 * @method Requirment setName()         Sets the current record's "name" value
 * @method Requirment setVersion()      Sets the current record's "version" value
 * @method Requirment setRepository()   Sets the current record's "Repository" value
 * 
 * @package    symfohub
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRequirment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('requirment');
        $this->hasColumn('repostory_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'symfony',
              1 => 'orm',
              2 => 'javascript',
             ),
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('version', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Repository', array(
             'local' => 'repostory_id',
             'foreign' => 'id'));
    }
}