<?php

/**
 * BaseAssertion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $repository_id
 * @property integer $user_id
 * @property enum $works
 * @property string $comment
 * @property string $body
 * @property Repository $Repository
 * @property doGitHubUser $User
 * 
 * @method integer      getRepositoryId()  Returns the current record's "repository_id" value
 * @method integer      getUserId()        Returns the current record's "user_id" value
 * @method enum         getWorks()         Returns the current record's "works" value
 * @method string       getComment()       Returns the current record's "comment" value
 * @method string       getBody()          Returns the current record's "body" value
 * @method Repository   getRepository()    Returns the current record's "Repository" value
 * @method doGitHubUser getUser()          Returns the current record's "User" value
 * @method Assertion    setRepositoryId()  Sets the current record's "repository_id" value
 * @method Assertion    setUserId()        Sets the current record's "user_id" value
 * @method Assertion    setWorks()         Sets the current record's "works" value
 * @method Assertion    setComment()       Sets the current record's "comment" value
 * @method Assertion    setBody()          Sets the current record's "body" value
 * @method Assertion    setRepository()    Sets the current record's "Repository" value
 * @method Assertion    setUser()          Sets the current record's "User" value
 * 
 * @package    symfohub
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAssertion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('assertion');
        $this->hasColumn('repository_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('works', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'yes',
              1 => 'patch',
              2 => 'no',
              3 => 'old',
             ),
             ));
        $this->hasColumn('comment', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('body', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Repository', array(
             'local' => 'repository_id',
             'foreign' => 'id'));

        $this->hasOne('doGitHubUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}