<?php

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $repository_id
 * @property integer $user_id
 * @property string $title
 * @property clob $body
 * @property clob $html
 * @property boolean $is_recommendation
 * @property Repository $Repository
 * @property doGitHubUser $User
 * 
 * @method integer      getRepositoryId()      Returns the current record's "repository_id" value
 * @method integer      getUserId()            Returns the current record's "user_id" value
 * @method string       getTitle()             Returns the current record's "title" value
 * @method clob         getBody()              Returns the current record's "body" value
 * @method clob         getHtml()              Returns the current record's "html" value
 * @method boolean      getIsRecommendation()  Returns the current record's "is_recommendation" value
 * @method Repository   getRepository()        Returns the current record's "Repository" value
 * @method doGitHubUser getUser()              Returns the current record's "User" value
 * @method Post         setRepositoryId()      Sets the current record's "repository_id" value
 * @method Post         setUserId()            Sets the current record's "user_id" value
 * @method Post         setTitle()             Sets the current record's "title" value
 * @method Post         setBody()              Sets the current record's "body" value
 * @method Post         setHtml()              Sets the current record's "html" value
 * @method Post         setIsRecommendation()  Sets the current record's "is_recommendation" value
 * @method Post         setRepository()        Sets the current record's "Repository" value
 * @method Post         setUser()              Sets the current record's "User" value
 * 
 * @package    symfohub
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('repository_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('html', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_recommendation', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Repository', array(
             'local' => 'repository_id',
             'foreign' => 'id'));

        $this->hasOne('doGitHubUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}