<?php

/**
 * DocumentationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Documentation');
    }
}