<?php

/**
 * RequirementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RequirementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RequirementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Requirement');
    }
}