<?php

/**
 * RequirmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RequirmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RequirmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Requirment');
    }
}