# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  host: # host

  github:
    username:
    password:

all:
  # register your app at https://github.com/account/applications/new
  doGitHubPlugin:
    client_id:     # provided by GitHub 
    client_secret: # provided by GitHub 
    redirect_url:  # 'http://YOURURL/github_auth'

  symfony:
    version: [1.0, 1.2, 1.4, 2]
    doctrine: [1.2, 2, Doctrator]
    propel: [1.4, 1.5]
    view: [PHP, Twig]
    nosql: [MongoDB, Memcache, Redis]
    license: [MIT, GPL, LGPL, BSD, Apache 2.0]

  bundle:
    version: [2]
    doctrine: [2, Doctrator]

  plugin:
    version: [1.0, 1.1, 1.2, 1.3, 1.4]
    doctrine: [1.2]
    javascript: [jQuery, Prototype, ExtJS, Dojo, MooTools]

  disqus:
    secret_key: # provided by disqus
