# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [screen.css, twilight.css]

  javascripts:    [jquery.js, jquery.raty.js, jquery.bubblepopup.v2.3.1.min.js, main.js]

  has_layout:     true
  layout:         layout
