<?php

/**
 * BasedoGitHubRemember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $remember_key
 * @property integer $user_id
 * @property string $access_token
 * @property doGitHubUser $doGitHubUser
 * 
 * @method string           getRememberKey()  Returns the current record's "remember_key" value
 * @method integer          getUserId()       Returns the current record's "user_id" value
 * @method string           getAccessToken()  Returns the current record's "access_token" value
 * @method doGitHubUser     getDoGitHubUser() Returns the current record's "doGitHubUser" value
 * @method doGitHubRemember setRememberKey()  Sets the current record's "remember_key" value
 * @method doGitHubRemember setUserId()       Sets the current record's "user_id" value
 * @method doGitHubRemember setAccessToken()  Sets the current record's "access_token" value
 * @method doGitHubRemember setDoGitHubUser() Sets the current record's "doGitHubUser" value
 * 
 * @package    symfohub
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasedoGitHubRemember extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('do_git_hub_remember');
        $this->hasColumn('remember_key', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('access_token', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('doGitHubUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}