<?php

/**
 * TwitterTweetLastFetchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TwitterTweetLastFetchTable extends PluginTwitterTweetLastFetchTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TwitterTweetLastFetchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TwitterTweetLastFetch');
    }
}