<?php

/**
 * TwitterTweetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TwitterTweetTable extends PluginTwitterTweetTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TwitterTweetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TwitterTweet');
    }
}