<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addrepositoryrate extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('repository_rate', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'primary' => true,
             ),
             'rate' => 
             array(
              'range' => 
              array(
              1 => 5,
              ),
              'type' => 'float',
              'length' => NULL,
             ),
             'comment' => 
             array(
              'type' => 'string',
              'length' => 4000,
             ),
             'do_git_hub_user_id' => 
             array(
              'primary' => true,
              'type' => 'bigint',
              'length' => 20,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'do_git_hub_user_id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('repository_rate');
    }
}