<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddogithubuser extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('do_git_hub_user', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'username' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('do_git_hub_user');
    }
}