<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddocumentation extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('documentation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'repository_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'text' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'html' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('documentation');
    }
}