<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtag extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('tag', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'is_triple' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'triple_namespace' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'triple_key' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'triple_value' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             ), array(
             'indexes' => 
             array(
              'name' => 
              array(
              'fields' => 
              array(
               0 => 'name',
              ),
              ),
              'triple1' => 
              array(
              'fields' => 
              array(
               0 => 'triple_namespace',
              ),
              ),
              'triple2' => 
              array(
              'fields' => 
              array(
               0 => 'triple_key',
              ),
              ),
              'triple3' => 
              array(
              'fields' => 
              array(
               0 => 'triple_value',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('tag');
    }
}