<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtagging extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('tagging', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'tag_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'taggable_model' => 
             array(
              'type' => 'string',
              'length' => 30,
             ),
             'taggable_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
              'tag' => 
              array(
              'fields' => 
              array(
               0 => 'tag_id',
              ),
              ),
              'taggable' => 
              array(
              'fields' => 
              array(
               0 => 'taggable_model',
               1 => 'taggable_id',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('tagging');
    }
}