<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addrequirement extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('requirement', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'repository_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'symfony',
              1 => 'doctrine',
              2 => 'propel',
              3 => 'javascript',
              4 => 'license',
              ),
              'length' => NULL,
             ),
             'value' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('requirement');
    }
}