<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpost extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('post', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'repository_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'body' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'html' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'author' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('post');
    }
}