<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('do_git_hub_remember', 'do_git_hub_remember_user_id_do_git_hub_user_id', array(
             'name' => 'do_git_hub_remember_user_id_do_git_hub_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'do_git_hub_user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('documentation', 'documentation_repository_id_repository_id', array(
             'name' => 'documentation_repository_id_repository_id',
             'local' => 'repository_id',
             'foreign' => 'id',
             'foreignTable' => 'repository',
             ));
        $this->createForeignKey('post', 'post_repository_id_repository_id', array(
             'name' => 'post_repository_id_repository_id',
             'local' => 'repository_id',
             'foreign' => 'id',
             'foreignTable' => 'repository',
             ));
        $this->createForeignKey('requirement', 'requirement_repository_id_repository_id', array(
             'name' => 'requirement_repository_id_repository_id',
             'local' => 'repository_id',
             'foreign' => 'id',
             'foreignTable' => 'repository',
             ));
        $this->createForeignKey('requirment', 'requirment_repostory_id_repository_id', array(
             'name' => 'requirment_repostory_id_repository_id',
             'local' => 'repostory_id',
             'foreign' => 'id',
             'foreignTable' => 'repository',
             ));
        $this->createForeignKey('repository_rate', 'repository_rate_id_repository_id', array(
             'name' => 'repository_rate_id_repository_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'repository',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('repository_rate', 'repository_rate_do_git_hub_user_id_do_git_hub_user_id', array(
             'name' => 'repository_rate_do_git_hub_user_id_do_git_hub_user_id',
             'local' => 'do_git_hub_user_id',
             'foreign' => 'id',
             'foreignTable' => 'do_git_hub_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('do_git_hub_remember', 'do_git_hub_remember_user_id_do_git_hub_user_id');
        $this->dropForeignKey('documentation', 'documentation_repository_id_repository_id');
        $this->dropForeignKey('post', 'post_repository_id_repository_id');
        $this->dropForeignKey('requirement', 'requirement_repository_id_repository_id');
        $this->dropForeignKey('requirment', 'requirment_repostory_id_repository_id');
        $this->dropForeignKey('repository_rate', 'repository_rate_id_repository_id');
        $this->dropForeignKey('repository_rate', 'repository_rate_do_git_hub_user_id_do_git_hub_user_id');
    }
}