<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('requirment');
        $this->addColumn('twitter_tweets', 'keyword', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->createTable('requirment', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'repostory_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'symfony',
              1 => 'orm',
              2 => 'javascript',
              ),
              'length' => '',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'version' => 
             array(
              'type' => 'string',
              'length' => '5',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->removeColumn('twitter_tweets', 'keyword');
    }
}