<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('twitter_tweets', 'keyword', array(
             'fields' => 
             array(
              0 => 'keyword',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('twitter_tweets', 'keyword', array(
             'fields' => 
             array(
              0 => 'keyword',
             ),
             ));
    }
}