<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('documentation', 'text_hash', 'string', '32', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('documentation', 'text_hash');
    }
}