<?php

/**
 * doGitHubRememberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class doGitHubRememberTable extends PlugindoGitHubRememberTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object doGitHubRememberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('doGitHubRemember');
    }
}