<?php

/**
 * doGitHubUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class doGitHubUserTable extends PlugindoGitHubUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object doGitHubUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('doGitHubUser');
    }

    /**
     * @param string $username
     * @return doGitHubUser
     */
    public function findOrCreateByUsername($username) {
        $user = $this->findOneByUsername($username);
        if (!$user) {
          try {
            $gitHub = new phpGitHubApi();
            $userInfo = $gitHub->getUserApi()->show($username);
          } catch (Exception $e) {
            sleep(60);
            $userInfo = $gitHub->getUserApi()->show($username);
          }
          $user = new doGitHubUser();
          $user->username = $username;
          if (isset($userInfo['email'])) $user->email = $userInfo['email'];
          // TODO add other fields
          $user->save();
          
        }
        return $user;
    }

}