<?php

/**
 * doGitHubUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfohub
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class doGitHubUser extends PlugindoGitHubUser {
  
  public function getAvatar($size = 40) {
    return "http://www.gravatar.com/avatar/" . md5(strtolower(trim($this->email))) . "?s=".$size;
  }
  
}
