<?php

/**
 * PlugindoGitHubRememberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugindoGitHubRememberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugindoGitHubRememberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugindoGitHubRemember');
    }
}